version: '3.8'

services:
  app:
    build: .
    ports:
      - "5001:5001"  
    restart: always
    networks:
      - webnet

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80" 
    depends_on:
      - app
    networks:
      - webnet

networks:
  webnet:
